package pokemon;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author SamuelD
 */
public class Jeu extends javax.swing.JFrame {

    /**
     * Creates new form Jeu
     */
    public Jeu() {
        initComponents();
    }

    // permet d'obtenir un nombre au hasard pour la variable "lignes"
    Random rn = new Random();
int n = 100;
int ligne = rn.nextInt() % n;


    ImageIcon poke = new ImageIcon("3.png"); 
    int poke1, poke2; // pokemons du joueur et de l'ordi
    int attack1, attack2; // attaques du joueur et de l'ordi
    String score1,score2; // scores du joueur et de l'ordi en String pour pouvoir les afficher 
    int iscore1 = 200; // score de depart du joueur en int 
    int iscore2 = 200;  // score de depart de l'ordi en int 
    
    // des conversions seront donc effectuees entre iscore1 et score1, iscore2 et score2
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jeu = new javax.swing.JPanel();
        Attaque = new javax.swing.JComboBox<>();
        Pokemon2 = new javax.swing.JLabel();
        PV2C = new javax.swing.JLabel();
        PV1C = new javax.swing.JLabel();
        PV2 = new javax.swing.JLabel();
        PV1 = new javax.swing.JLabel();
        Pokemon1 = new javax.swing.JLabel();
        Regles = new javax.swing.JButton();
        Attaquer = new javax.swing.JButton();
        ImgFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESIEA Pokemon");
        setMinimumSize(new java.awt.Dimension(638, 392));
        setResizable(false);

        Jeu.setLayout(null);

        Attaque.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Attaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attaque 1", "Attaque 2", "Attaque 3", "Attaque 4", "Attaque 5" }));
        Attaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttaqueActionPerformed(evt);
            }
        });
        Jeu.add(Attaque);
        Attaque.setBounds(60, 300, 140, 40);

        Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/11.png"))); // NOI18N
        Jeu.add(Pokemon2);
        Pokemon2.setBounds(450, 100, 130, 130);

        PV2C.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        PV2C.setText("200");
        Jeu.add(PV2C);
        PV2C.setBounds(540, 240, 40, 40);

        PV1C.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        PV1C.setText("200");
        Jeu.add(PV1C);
        PV1C.setBounds(140, 250, 40, 30);

        PV2.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        PV2.setText("PV :");
        Jeu.add(PV2);
        PV2.setBounds(480, 240, 60, 40);

        PV1.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        PV1.setText("PV :");
        Jeu.add(PV1);
        PV1.setBounds(80, 250, 60, 30);

        Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/2.png"))); // NOI18N
        Jeu.add(Pokemon1);
        Pokemon1.setBounds(60, 90, 130, 150);

        Regles.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        Regles.setText("Regles");
        Regles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReglesActionPerformed(evt);
            }
        });
        Jeu.add(Regles);
        Regles.setBounds(470, 300, 140, 40);

        Attaquer.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        Attaquer.setText("Attaquer !");
        Attaquer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttaquerActionPerformed(evt);
            }
        });
        Jeu.add(Attaquer);
        Attaquer.setBounds(250, 290, 140, 50);

        ImgFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/Pokemon.jpg"))); // NOI18N
        Jeu.add(ImgFond);
        ImgFond.setBounds(-9, -4, 640, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jeu, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jeu, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ReglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReglesActionPerformed
        Regles f3 = new Regles();
        f3.setVisible(true);
        
    }//GEN-LAST:event_ReglesActionPerformed

    private void AttaquerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttaquerActionPerformed
     if (ligne < 0) { ligne = -(ligne); } 
         poke1 = ReadCsv.getpokemon1(ligne); // recupere la valeur du pokemon1 et la met dans "poke1"
         poke2 = ReadCsv.getpokemon2(ligne); // recupere la valeur du pokemon2 et la met dans "poke2"
         
         // change l'image de Pokemon1 suivant la valeur obtenue par poke1
         if (poke1 == 1) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/1.png"))); }
         if (poke1 == 2) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/2.png"))); }
         if (poke1 == 3) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/3.png"))); }
         if (poke1 == 4) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/4.png"))); }
         if (poke1 == 5) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/5.png"))); }
         if (poke1 == 6) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/6.png"))); }
         if (poke1 == 7) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/7.png"))); }
         if (poke1 == 8) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/8.png"))); }
         if (poke1 == 9) { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/9.png"))); }
         if (poke1 == 10 )  { Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/10.png"))); }
         
         // change l'image de Pokemon2 suivant la valeur obtenue par poke2
         if (poke2 == 1) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/1.png"))); }
         if (poke2 == 2) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/2.png"))); }
         if (poke2 == 3) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/3.png"))); }
         if (poke2 == 4) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/4.png"))); }
         if (poke2 == 5) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/5.png"))); }
         if (poke2 == 6) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/6.png"))); }
         if (poke2 == 7) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/7.png"))); }
         if (poke2 == 8) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/8.png"))); }
         if (poke2 == 9) { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/9.png"))); }
         if (poke2 == 10 )  { Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/10.png"))); }
         
         // Gestion des 5 attaques proposees au joueur
         // si l'attaque 1 est choisie par le joueur on passe 1 en argument dans getAttack1();
       if (Attaque.getSelectedItem().equals("Attaque 1")) { attack1 = ReadCsv.getAttack1(1,ligne); 
                                                             attack2 = ReadCsv.getAttack2(ligne);
       }
         if (Attaque.getSelectedItem().equals("Attaque 2")) {  attack1 = ReadCsv.getAttack1(2,ligne);
                                                               attack2 = ReadCsv.getAttack2(ligne);
       }
           if (Attaque.getSelectedItem().equals("Attaque 3")) {  attack1 = ReadCsv.getAttack1(3,ligne);
                                                                 attack2 = ReadCsv.getAttack2(ligne);
       }
          if (Attaque.getSelectedItem().equals("Attaque 4")) {  attack1 = ReadCsv.getAttack1(4,ligne);
                                                                attack2 = ReadCsv.getAttack2(ligne);
       }
         if (Attaque.getSelectedItem().equals("Attaque 5")) {  attack1 = ReadCsv.getAttack1(5,ligne);
                                                               attack2 = ReadCsv.getAttack2(ligne);
       }
         iscore1 = iscore1 - attack2; // mise a jour du score du joueur
         iscore2 = iscore2 - attack1; // mise à jour du score de l'ordi
         
         // en cas de match nul
         // c'est le cas qu'il faut traiter en premier pour eviter que le joueur ou l'ordi soit vainqueur alors que c'est un match nul
            if (iscore1 <= 0 && iscore2 <= 0)
            { iscore1 = 0; iscore2 = 0; // mets les scores a 0
         score1 = Integer.toString(iscore1); // convertit iscore1 en score1 qui est un String
         PV1C.setText(score1); // on remplace le dernier score1 par le nouveau score1
         score2 = Integer.toString(iscore2);
         PV2C.setText(score2); 
         JOptionPane.showMessageDialog(null, "                0-0 ","Match nul", JOptionPane.INFORMATION_MESSAGE,poke);
         Bienvenue f1 = new Bienvenue(); 
        f1.setVisible(true);
        this.setVisible(false);
         
         }
         
         // si le joueur perd 
         if (iscore1 <= 0) { iscore1 = 0;
         score1 = Integer.toString(iscore1);
         PV1C.setText(score1);
         score2 = Integer.toString(iscore2);
         PV2C.setText(score2); 
         JOptionPane.showMessageDialog(null, "Perseverez pour la prochaine fois", "Vous avez perdu !", JOptionPane.INFORMATION_MESSAGE,poke);
         Bienvenue f1 = new Bienvenue();  // appelle une nouvelle fenetre
        f1.setVisible(true);        // affiche la fenetre          
        this.setVisible(false);    // ferme la fenetre actuelle
         
         }
         // si l'ordinateur perd
         if (iscore2 <= 0) { iscore2 = 0;
         score1 = Integer.toString(iscore1);
         PV1C.setText(score1);
         score2 = Integer.toString(iscore2);
         PV2C.setText(score2); 
         JOptionPane.showMessageDialog(null, "Bravo à vous", "Vous êtes victorieux !", JOptionPane.INFORMATION_MESSAGE,poke);
         Bienvenue f1 = new Bienvenue(); 
        f1.setVisible(true);
        this.setVisible(false);
        
         }
         
         // mise a jour de la partie lorsqu'aucun des 2 joueurs n'est a zero
     score1 = Integer.toString(iscore1); // conversion en String
         PV1C.setText(score1); // le nouveau score1 remplace l'ancien score1
         score2 = Integer.toString(iscore2);
         PV2C.setText(score2); 
         
          
    }//GEN-LAST:event_AttaquerActionPerformed

    private void AttaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttaqueActionPerformed
    }//GEN-LAST:event_AttaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Jeu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Attaque;
    private javax.swing.JButton Attaquer;
    private javax.swing.JLabel ImgFond;
    private javax.swing.JPanel Jeu;
    private javax.swing.JLabel PV1;
    private javax.swing.JLabel PV1C;
    private javax.swing.JLabel PV2;
    private javax.swing.JLabel PV2C;
    private javax.swing.JLabel Pokemon1;
    private javax.swing.JLabel Pokemon2;
    private javax.swing.JButton Regles;
    // End of variables declaration//GEN-END:variables
}
