package pokemon;

/**
 *
 * @author SamuelD
 */
public class Regles extends javax.swing.JFrame {

    /**
     * Creates new form Regles
     */
    public Regles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regles = new javax.swing.JPanel();
        JaiCompris = new javax.swing.JButton();
        ZoneTexte = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ImgFond = new javax.swing.JLabel();

        setTitle("ESIEA Pokemon");
        setMaximumSize(new java.awt.Dimension(646, 394));
        setMinimumSize(new java.awt.Dimension(646, 394));
        setPreferredSize(new java.awt.Dimension(646, 394));
        setResizable(false);

        Regles.setLayout(null);

        JaiCompris.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JaiCompris.setText("J'ai compris !");
        JaiCompris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JaiComprisActionPerformed(evt);
            }
        });
        Regles.add(JaiCompris);
        JaiCompris.setBounds(210, 300, 230, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Une ligne correspondant à un tirage est récupérée\nau hasard les deux complémentaires \ncorrespondent à deux Pokemons qui vont se battre.\nPuis l'utilisateur va rentrer en cliquant sur le bouton jouer\nun chiffre entre un et cinq\nqui correspond a un des 5 numéros tirés.Le numéro sera \nle nombre de pv infligé à l'adversaire.\nPuis l’ordinateur fait la même chose avec un rand.\nEt ça recommence jusqu'à ce que l'un des Pokemon ait 0 pv.\n\n\n\n");
        ZoneTexte.setViewportView(jTextArea1);

        Regles.add(ZoneTexte);
        ZoneTexte.setBounds(30, 110, 600, 170);

        ImgFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/Pokemon.jpg"))); // NOI18N
        ImgFond.setMaximumSize(new java.awt.Dimension(646, 395));
        ImgFond.setMinimumSize(new java.awt.Dimension(646, 395));
        ImgFond.setPreferredSize(new java.awt.Dimension(646, 395));
        Regles.add(ImgFond);
        ImgFond.setBounds(0, 0, 640, 358);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Regles, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Regles, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JaiComprisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JaiComprisActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JaiComprisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Regles().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgFond;
    private javax.swing.JButton JaiCompris;
    private javax.swing.JPanel Regles;
    private javax.swing.JScrollPane ZoneTexte;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
